### PR TITLE
Propose ranged key iteration excluding end_key

### PR DESCRIPTION
**Pull request by xitep**

### CODE REVIEW

**Comment by vhbit** [comment]
hey, nice catch of bug in cursor initialization!

I dislike `curr_cursor_lte` though. What I'd be happier to see is a combination of:
- method on cursor like `fn cmp_cur_key(&self, test_key) -> std::cmp::Ordering` 
- taking decision based on this result: 
```
let cmp = cursor.cmp_cur_key(end_key);
cmp == Ordering::Less || (cmp == Ordering::Equal && allow_equality)
```

It can be done inline or as an utility function in form `is_less(cursor.cmp_cur_key(end_key), exclude_end)` or even as a method for `cmp::Ordering` like `cursor.cmp_cur_key(end_key).is_less(exclude_end)`

**Comment by xitep** [comment]
thanks for your feedback, i'll see what i can do

**Comment by xitep** [comment]
i've chosen the `cursor.cmp_cur_key(end_key).is_less(exclude_end)` approach which needed a private trait (`IsLess` in this example). hope this is fine with you.

**Comment by vhbit** [comment]
Thanks!

**Pull request merged**
